spring:
  application:
    name: ms-ux-orchestrator

server:
  port: 9991

services:
  transaction:
    base-url: http://localhost:9992
    timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    pe.com.yape.orchestrator: INFO
    org.springframework.web.reactive: DEBUG

