spring:
  application:
    name: ms-ux-orchestrator

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    pe.com.yape.orchestrator: INFO

